# Generated by Django 6.0.5 on 2026-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
